[build]
  command = "npm run build"
  publish = "build"

[[redirects]]
  from = "/"
  to = "/movies/now_playing"
  status = 302

[[redirects]]
  from = "/movies/popular"
  to = "/movies/popular"
  status = 302

[[redirects]]
  from = "/movies/top"
  to = "/movies/top"
  status = 302

[[redirects]]
  from = "/movies/upcoming"
  to = "/movies/upcoming"
  status = 302

[[redirects]]
  from = "/search"
  to = "/search"
  status = 302
